version: "2"
services:

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"

  registrator:
    image: gliderlabs/registrator
    command: -internal consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on: [consul]

  requisition-refui:
    image: openlmis/requisition-refui:3.0.0-SNAPSHOT
    env_file: .env
    environment:
      # Changing the virtual location affects loading of the assets on UI. Handle with care.
      - VIRTUAL_LOCATION=public
    depends_on: [consul]

  requisition:
    image: openlmis/requisition:3.0.0-SNAPSHOT
    env_file: .env
    environment:
      VIRTUAL_LOCATION: requisition
      JAVA_OPTS: '-Dlogging.config=/logback.xml -Dspring.jpa.properties.hibernate.hbm2ddl.import_files=/bootstrap.sql,file:///demo-data/data.sql'
    volumes:
      - './logback.xml:/logback.xml'
    depends_on: [log]

  referencedata:
    image: openlmis/referencedata:3.0.0-SNAPSHOT
    env_file: .env
    environment:
      VIRTUAL_LOCATION: referencedata
      JAVA_OPTS: '-Dlogging.config=/logback.xml -Dspring.jpa.properties.hibernate.hbm2ddl.import_files=/bootstrap.sql,file:///demo-data/data.sql'
    volumes:
      - './logback.xml:/logback.xml'
    depends_on: [log]

  auth:
    image: openlmis/auth:3.0.0-SNAPSHOT
    env_file: .env
    environment:
      VIRTUAL_LOCATION: auth
      JAVA_OPTS: '-Dlogging.config=/logback.xml -Dspring.jpa.properties.hibernate.hbm2ddl.import_files=/bootstrap.sql,file:///demo-data/data.sql'
    volumes:
      - './logback.xml:/logback.xml'
    depends_on: [log]

  notification:
    image: openlmis/notification:3.0.0-SNAPSHOT
    env_file: .env
    environment:
      VIRTUAL_LOCATION: notification
      JAVA_OPTS: '-Dlogging.config=/logback.xml'
    volumes:
      - './logback.xml:/logback.xml'
    depends_on: [log]

  fulfillment:
    image: openlmis/fulfillment:3.0.0-SNAPSHOT
    env_file: .env
    environment:
      VIRTUAL_LOCATION: fulfillment
      JAVA_OPTS: '-Dlogging.config=/logback.xml -Dspring.jpa.properties.hibernate.hbm2ddl.import_files=/bootstrap.sql,file:///demo-data/data.sql'
    volumes:
      - './logback.xml:/logback.xml'
    depends_on: [log]

  db:
    image: openlmis/postgres
    env_file: .env
    depends_on: [consul]

  log:
    image: openlmis/rsyslog
    volumes:
      - '../logs/requisition:/var/log'
    depends_on: [consul]

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/app/nginx.tmpl:ro
    depends_on: [consul]
