version: "0.1"
services:

  consul:
    command: -server -bootstrap
    image: gliderlabs/consul-server
    ports:
      - "8300"
      - "8400"
      - "8500:8500"
      - "53"

  nifi:
    image: apache/nifi:${OL_NIFI_VERSION}
    ports:
      - "8080"
      - "9443"

  db:
    image: openlmis/postgres:${OL_POSTGRES_VERSION}
    env_file: ../settings.env
    depends_on: [consul]
